compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
  # activation_checkpointing:
  #   partition_activations: true  # ZeRO-R: partitions activations across GPUs
  #   cpu_checkpointing: false     # Offload checkpointed activations to CPU (use if GPU memory is extremely tight)
  #   contiguous_memory_optimization: false # May improve performance but uses more memory
  #   synchronize_checkpoint_boundary: false
  #   profile: false # Set to true to get detailed profiling of checkpointing

distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false